// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgfddddbtbfgkakglrmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZmRkZGRidGJmZ2tha2dscm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjM5NDMsImV4cCI6MjA2ODQzOTk0M30.c6juSgP8U7Oof0bcMRiJXDnp-1jOjL3epZCrE3mm-cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});